services:

  ############################################################
  # Jenkins
  ############################################################
  jenkins:

    build:
      context: ./jenkins
      dockerfile: Dockerfile

    image: rasnas-jenkins:latest

    container_name: jenkins

    hostname: jenkins

    restart: unless-stopped

    privileged: true

    ports:
      - "8080:8080"
      - "50000:50000"

    environment:
      TZ: Asia/Kolkata

    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - devsecops

  ############################################################
  # PostgreSQL
  ############################################################
  postgres:

    image: postgres:16

    container_name: postgres

    hostname: postgres

    restart: unless-stopped

    environment:

      POSTGRES_DB: devsecops

      POSTGRES_USER: postgres

      POSTGRES_PASSWORD: postgres123

      TZ: Asia/Kolkata

    ports:

      - "5432:5432"

    volumes:

      - postgres_data:/var/lib/postgresql/data

    healthcheck:

      test: ["CMD-SHELL", "pg_isready -U postgres"]

      interval: 10s

      timeout: 5s

      retries: 5

    networks:

      - devsecops

  ############################################################
  # Grafana
  ############################################################
  grafana:

    image: grafana/grafana-oss:latest

    container_name: grafana

    hostname: grafana

    restart: unless-stopped

    depends_on:

      postgres:
        condition: service_healthy

    environment:

      GF_SECURITY_ADMIN_USER: admin

      GF_SECURITY_ADMIN_PASSWORD: admin123

      GF_USERS_ALLOW_SIGN_UP: "false"

      TZ: Asia/Kolkata

    ports:

      - "3000:3000"

    volumes:

      - grafana_data:/var/lib/grafana

    networks:

      - devsecops

############################################################
# Volumes
############################################################

volumes:

  jenkins_home:

  postgres_data:

  grafana_data:

############################################################
# Network
############################################################

networks:

  devsecops:

    driver: bridge
