# ============================================================
# File: 01-namespace.yaml
#
# Purpose:
# Creates an isolated namespace for our DevSecOps project.
#
# Why Namespace?
#
# Kubernetes clusters can host multiple applications.
#
# Instead of deploying everything into the "default" namespace,
# we create our own namespace.
#
# Benefits:
#
# - Isolation
# - Easy cleanup
# - Better organization
# - Production best practice
#
# Delete everything later using:
#
# kubectl delete namespace devsecops
#
# ============================================================

apiVersion: v1

# We are creating a Namespace resource.
kind: Namespace

metadata:

  # Namespace name
  name: devsecops
