# ============================================================
# File: 02-nginx-deployment.yaml
#
# Purpose
#
# Deploy one NGINX web server inside Kubernetes.
#
# Kubernetes NEVER creates containers directly.
#
# Instead
#
# Deployment
#        ↓
# ReplicaSet
#        ↓
# Pod
#        ↓
# Container
#
# ============================================================

apiVersion: apps/v1

# Deployment manages Pods.
kind: Deployment

metadata:

  # Deployment name
  name: nginx

  # Deploy inside our namespace
  namespace: devsecops

spec:

  # Number of pod copies
  replicas: 1

  # Select pods having label app=nginx
  selector:
    matchLabels:
      app: nginx

  template:

    metadata:

      labels:
        app: nginx

    spec:

      containers:

      - name: nginx

        image: nginx:latest

        imagePullPolicy: Always

        ports:

        - containerPort: 80
