# ============================================================
# File: 03-nginx-service.yaml
#
# Pods are temporary.
#
# Their IP addresses change.
#
# Service creates a permanent endpoint.
#
# Service Types
#
# ClusterIP
# NodePort
# LoadBalancer
#
# We'll use NodePort because Minikube
# doesn't have a cloud load balancer.
#
# ============================================================

apiVersion: v1

kind: Service

metadata:

  name: nginx-service

  namespace: devsecops

spec:

  selector:

    app: nginx

  ports:

  - protocol: TCP

    port: 80

    targetPort: 80

  type: NodePort
