# ======================================================
# File: 04-configmap.yaml
#
# ConfigMap stores NON-SENSITIVE configuration.
#
# Examples:
# - Application Name
# - Environment
# - Database Host
# - Logging Level
#
# Never store passwords here.
#
# ======================================================

apiVersion: v1

kind: ConfigMap

metadata:
  name: app-config
  namespace: devsecops

data:

  APP_NAME: "AI DevSecOps Platform"

  ENVIRONMENT: "Development"

  LOG_LEVEL: "INFO"

  COMPANY: "CDAC"
