# ======================================================
# Secrets store sensitive data.
#
# Examples:
#
# Passwords
# API Keys
# Tokens
#
# Kubernetes stores them Base64 encoded.
#
# ======================================================

apiVersion: v1

kind: Secret

metadata:
  name: postgres-secret
  namespace: devsecops

type: Opaque

data:

  username: YWRtaW4=

  password: cGFzc3dvcmQ=
