# =============================================================
# PostgreSQL Persistent Volume Claim
#
# Requests 5 GB of storage.
#
# Minikube dynamically provisions the volume.
#
# =============================================================

apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: postgres-pvc
  namespace: devsecops

spec:

  accessModes:
    - ReadWriteOnce

  resources:

    requests:

      storage: 5Gi
